name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  
  test:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run build
        pm2 stop npm
        pm2 start npm
      env:
        CI: true
           
    - name: Lint Dockerfile
      uses: brpaz/hadolint-action@master
      with:
          dockerfile: ./Dockerfile

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ secrets.SSH_PORT }}
      
        script: |
          mkdir -p ~/my-express-app/
          cd ~/my-express-app/
          git clone https://github.com/sagarshrestha24/myproject.git
          cd ~/myproject
          docker-compose build
   


      
  
  
